{php}
//DO NOT EDIT THIS TEMPLATE WITHOUT PERMISSION FROM KEVIN ORILEY
  
    require_once 'inc/MCAPI.class.php';
    $apikey="625fe830ae378113cdfa0d1686e685a6-us1";
     $api = new MCAPI($apikey);
     //$groups1 = $api->listInterestGroupings("e24d246ce5");
     //print_r( $groups1);
     $email=$_POST['emailx'];
     $fname=$_POST['fname'];
     $lname=$_POST['lname'];
     $groups = array();
     $club417 = $_POST['updates_offers'];
     $bestOfTheWeek = $_POST['botw'];
     $tableTalk = $_POST['table_talk'];
     $rightAtHome = $_POST['right_at_home'];
     $shopTalk = $_POST['shop_talk'];
     $brideBuzz = $_POST['bridal_buzz'];
     $weekendPass = $_POST['weekend_pass'];


   if($email != ''){
     if($club417 == 'on'){ array_push($groups, array('name'=>'417 Magazine Club 417', 'groups'=>'Club 417'));}
     if($bestOfTheWeek == 'on'){ array_push($groups, array('name'=>'417 Magazine Best of the Week', 'groups'=>'Best of the Week'));}
     if($tableTalk == 'on'){ array_push($groups, array('name'=>'417 Magazine Table Talk', 'groups'=>'Table Talk'));}
     if($rightAtHome == 'on'){ array_push($groups, array('name'=>'417 Magazine Right at Home', 'groups'=>'Right at Home'));}
     if($shopTalk == 'on'){ array_push($groups, array('name'=>'417 Magazine Shop Talk', 'groups'=>'Shop Talk'));}
     if($brideBuzz == 'on'){ array_push($groups, array('name'=>'417 Magazine Bridal Buzz', 'groups'=>'Bridal Buzz'));}
     if($weekendPass == 'on'){ array_push($groups, array('name'=>'417 Magazine Weekend Pass', 'groups'=>'Weekend Pass '));}
     
     
     $merge_vars = array('FNAME'=>$fname, 'LNAME'=>$lname, 'GROUPINGS'=>$groups);


     $retval = $api->listSubscribe("e24d246ce5", $email, $merge_vars );

   } 
{/php}

{assign var="oaspos" value="Top1,Right1,x01,x10"}
{assign var="oascat" value=$xecategory|default:$Page->category|oasname}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title><PAGETITLE {if $cssname eq '417'}{$Page->tags[48].tag.title}{elseif $cssname eq 'home'}{$Page->tags[68].tag.title}{elseif $cssname eq 'bride'}{$Page->tags[105].tag.title}{/if}></title>
<meta name="robots" content="all" />
<meta name="Description" content="{$Page->description|default:$issue.description|default:$publication.description}" />
<meta name="Keywords" content="{$Page->keywords|default:$issue.keywords|default:$publication.keywords}" />
<link href="/themes/Local/css/417-2010.css" rel="stylesheet" type="text/css" />
<link href="/themes/Local/css/417-2013.css" rel="stylesheet" type="text/css" />
<link href="/themes/Local/css/417-landing-re.css" rel="stylesheet" type="text/css" />
<link href="/themes/Local/css/wrapper.css" rel="stylesheet" type="text/css" />
<link href='http://cdn-images.mailchimp.com/embedcode/slim-081711.css' rel='stylesheet' type='text/css'>


{include file="oas_head.tpl"}
<!-- Generated by OpenX 2.6.3 -->
<script type='text/javascript' src='http://badads.com/openx/www/delivery/spcjs.php?id=1'></script>
<script type="text/javascript" src="flowplayer-3.0.2.min.js"></script>
<script src="http://code.jquery.com/jquery-1.4.2.min.js"></script>
<link rel="stylesheet" type="text/css" href="/themes/Local/js/shadowbox.css">
<script type="text/javascript" src="/themes/Local/js/shadowbox.js"></script>
{literal}
<script type="text/javascript">
Shadowbox.init({
    // let's skip the automatic setup because we don't have any
    // properly configured link elements on the page
    skipSetup: true,
    // include the html player because we want to display some html content
    players: ["html"]
});

function dod(){

    // open a welcome message as soon as the window loads
    Shadowbox.open({
        content:    "<div style='position:relative;'><img src='http://417mag.com/images/gateway/DOTD_Gateway.gif' width='600' height='400' alt='' /><!-- Begin MailChimp Signup Form --><div id='mc_embed_signup' style='position:absolute; left:20px; top:250px; width:417px; background-color:'><form action='http://417mag.us1.list-manage2.com/subscribe/post?u=a8fed06de0b6d5d67d55d2487&amp;id=50e0803d24' method='post' id='mc-embedded-subscribe-form' name='mc-embedded-subscribe-form' class='validate' target='_blank'><input type='email' value='' name='EMAIL' class='email' id='mce-EMAIL' placeholder='email address' required style='width:100%'><div class='clear'><input type='submit' value='Subscribe' name='subscribe' id='mc-embedded-subscribe' class='button'></div></form></div><!--End mc_embed_signup--></div>",
        player:     "html",
        
        height:     400,
        width:      600
    });

};

function oneair(){

    // open a welcome message as soon as the window loads
    Shadowbox.open({
        content:    "<div><a href='http://badads.com/openx/www/delivery/ck.php?n=a218b5c4&amp;cb=INSERT_RANDOM_NUMBER_HERE' target='_blank'><img src='http://badads.com/openx/www/delivery/avw.php?campaignid=246&amp;cb=INSERT_RANDOM_NUMBER_HERE&amp;n=a218b5c4' border='0' alt='' /></a></div>",
        player:     "html",
        
        height:     400,
        width:      600
    });
};
function everkitchen(){

    // open a welcome message as soon as the window loads
    Shadowbox.open({
        content:    "<div><a href='http://badads.com/openx/www/delivery/ck.php?n=a9c5da9d&amp;cb=INSERT_RANDOM_NUMBER_HERE' target='_blank'><img src='http://badads.com/openx/www/delivery/avw.php?campaignid=311&amp;cb=INSERT_RANDOM_NUMBER_HERE&amp;n=a9c5da9d' border='0' alt='' /></a></div>",
        player:     "html",
        
        height:     590,
        width:      450
    });
};
    
function ash(){

    // open a welcome message as soon as the window loads
    Shadowbox.open({
        content:    "<div><a href='http://badads.com/openx/www/delivery/ck.php?n=a298dcf1&amp;cb=INSERT_RANDOM_NUMBER_HERE' target='_blank'><img src='http://badads.com/openx/www/delivery/avw.php?campaignid=375&amp;cb=INSERT_RANDOM_NUMBER_HERE&amp;n=a298dcf1' border='0' alt='' /></a></div>",
        player:     "html",
        
        height:     600,
        width:      600
    });
};
</script>
{/literal}
<script src="/themes/Local/js/jquery.instagram.js"></script>
{include file="417ga.tpl"}
</head>
{php}
//echo $_SESSION['oneair'];        
if($_SESSION['dod']=="1"){echo '<body onLoad="dod()">';}

elseif($_SESSION['oneair']=="1"){echo '<body onLoad="oneair()">';}
elseif($_SESSION['ek']=="1"){echo '<body onLoad="everkitchen()">';}
elseif($_SESSION['ash1']=="1"){echo '<body onLoad="ash()">';}
else{echo "<body>";}
{/php}
 <div id="page-container">
     
         <div id="fullWall"><!--/* OpenX Javascript Tag v2.8.9 */-->

<script type='text/javascript'><!--//<![CDATA[
   var m3_u = (location.protocol=='https:'?'https://badads.com/openx/www/delivery/ajs.php':'http://badads.com/openx/www/delivery/ajs.php');
   var m3_r = Math.floor(Math.random()*99999999999);
   if (!document.MAX_used) document.MAX_used = ',';
   document.write ("<scr"+"ipt type='text/javascript' src='"+m3_u);
   document.write ("?zoneid=71");
   document.write ('&amp;cb=' + m3_r);
   if (document.MAX_used != ',') document.write ("&amp;exclude=" + document.MAX_used);
   document.write (document.charset ? '&amp;charset='+document.charset : (document.characterSet ? '&amp;charset='+document.characterSet : ''));
   document.write ("&amp;loc=" + escape(window.location));
   if (document.referrer) document.write ("&amp;referer=" + escape(document.referrer));
   if (document.context) document.write ("&context=" + escape(document.context));
   if (document.mmm_fo) document.write ("&amp;mmm_fo=1");
   document.write ("'><\/scr"+"ipt>");
//]]>--></script><noscript><a href='http://badads.com/openx/www/delivery/ck.php?n=a206a4c8&amp;cb=INSERT_RANDOM_NUMBER_HERE' target='_blank'><img src='http://badads.com/openx/www/delivery/avw.php?zoneid=71&amp;cb=INSERT_RANDOM_NUMBER_HERE&amp;n=a206a4c8' border='0' alt='' /></a></noscript>
</div>
<div class="page-container">

{include file="top-417-2013.tpl"}
	<div id="page-body">
		<div style="clear:both; padding-bottom:5px;" >{loadModules position="headtag"}</div>
	 	<div id="column-1">				
			{loadModules position="left"}		
		</div>
	 	
			<div id="column-3">							  				  				  		
			{loadModules position="right"}
			</div>
			
</div>
                       <!--bottom ad -->
                        
                        <div class="clearfix" style="margin-top:5px; width:970px;">{loadModules position="bottom"}</div>
{include file="footer-417.tpl"}
</div>
        
    </div>
</body>
</html>
